# Generated by Django 4.1a1 on 2022-06-25 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0005_alter_amenity_options_alter_facility_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenity",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="facility",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="houserule",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="roomtype",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="file",
        ),
        migrations.AddField(
            model_name="photo",
            name="photo_file",
            field=models.ImageField(default="", upload_to="room_photos"),
        ),
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="rooms.amenity"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="facilities",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="rooms.facility"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="house_rules",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="rooms.houserule"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="rooms.roomtype",
            ),
        ),
    ]
