# Generated by Django 4.1a1 on 2022-06-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_rename_created_at_amenity_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="photo_file",
            new_name="file",
        ),
    ]
