# Generated by Django 4.1a1 on 2022-06-25 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0006_rename_created_at_amenity_created_and_more"),
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lists",
            old_name="created_at",
            new_name="created",
        ),
        migrations.AlterField(
            model_name="lists",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="lists", to="rooms.room"
            ),
        ),
        migrations.AlterField(
            model_name="lists",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
