# Generated by Django 4.1b1 on 2022-06-28 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_rename_photo_file_photo_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lists", "0002_rename_created_at_lists_created_alter_lists_rooms_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lists",
            new_name="List",
        ),
    ]
